import type {
  QuartzComponent,
  QuartzComponentConstructor,
  QuartzComponentProps,
  QuartzPluginData,
} from "@quartz-community/types"
import { resolveRelative } from "../util/path"
import style from "./styles/globalNav.scss"

/**
 * 글로벌 내비 — `Home | Topics | Archive | Notes`. 현재는 topbar 배치.
 *
 * · `condition`을 걸지 않는다 — 홈 포함 전 페이지에 항상 보여야 한다
 * · ⚠️ `position: "header"`는 쓸 수 없다. YAML 스키마 enum에 없고,
 *   config-loader의 positions 레코드도 left/right/beforeBody/afterBody 4개뿐이라
 *   등록해도 **에러 없이 조용히 버려진다**(사실상 죽은 슬롯)
 * · **Notes**는 전용 페이지가 없다. 노트 위에선 링크가 아닌 `<span>`으로 죽이고,
 *   그 밖에선 최신 노트로 보낸다. 전용 페이지가 생기면 static 항목으로 바꾸면 된다
 * · About은 자기소개 콘텐츠가 있어야 추가 가능. NAV_ITEMS에 항목만 넣으면 된다
 */

type NavItem =
  | { label: string; kind: "static"; slug: string }
  | { label: string; kind: "latest-note" }

const NAV_ITEMS: NavItem[] = [
  { label: "Home", kind: "static", slug: "index" },
  { label: "Topics", kind: "static", slug: "topics" },
  { label: "Archive", kind: "static", slug: "archive" },
  { label: "Notes", kind: "latest-note" },
]

// 노트가 하나도 없을 때 Notes의 목적지. 빈 아카이브가 깨진 링크보다 낫다.
const LATEST_NOTE_FALLBACK = "archive"

/**
 * ⚠️ `frontmatter.title` 유무로는 실제 노트를 걸러낼 수 없다 — folder-page /
 * tag-page 자동 생성 페이지, 404, topics/archive 가상 페이지 모두 title이 있다.
 */
function isAutoGeneratedPage(slug: string): boolean {
  return (
    slug.startsWith("tags/") ||
    slug === "index" ||
    slug.endsWith("/index") ||
    slug === "404" ||
    slug === "topics" ||
    slug === "archive"
  )
}

// recent-notes-index의 getSortTime과 같은 폴백 체인 — 홈 Recent Notes 맨 윗줄과
// Notes의 목적지가 항상 같은 노트여야 한다.
function getSortTime(f: QuartzPluginData & Record<string, unknown>): number {
  return f.dates?.modified?.getTime() ?? f.dates?.created?.getTime() ?? 0
}

function findLatestNoteSlug(allFiles: QuartzComponentProps["allFiles"]): string | null {
  let latest: (typeof allFiles)[number] | null = null
  for (const f of allFiles) {
    const slug = f.slug as string | undefined
    if (!slug || !f.frontmatter?.title || isAutoGeneratedPage(slug)) continue
    if (latest === null || getSortTime(f) > getSortTime(latest)) latest = f
  }
  return (latest?.slug as string | undefined) ?? null
}

export default (() => {
  const GlobalNav: QuartzComponent = ({
    allFiles,
    fileData,
    displayClass,
  }: QuartzComponentProps) => {
    const currentSlug = (fileData.slug as string) || "index"
    const onNote = !isAutoGeneratedPage(currentSlug) && Boolean(fileData.frontmatter?.title)

    return (
      <nav class={`${displayClass ?? ""} global-nav`}>
        {NAV_ITEMS.map((item) => {
          // 노트 위의 Notes는 자기 자신을 가리키게 두지 않는다 — 스크롤이 튀고
          // 히스토리만 쌓인다. 링크 자체를 없앤다.
          if (item.kind === "latest-note" && onNote) {
            return (
              <span class="global-nav-link active" aria-current="page">
                {item.label}
              </span>
            )
          }

          const isActive = item.kind === "static" && currentSlug === item.slug
          const targetSlug =
            item.kind === "static"
              ? item.slug
              : (findLatestNoteSlug(allFiles) ?? LATEST_NOTE_FALLBACK)

          return (
            <a
              class={`global-nav-link${isActive ? " active" : ""}`}
              href={resolveRelative(currentSlug, targetSlug)}
            >
              {item.label}
            </a>
          )
        })}
      </nav>
    )
  }

  GlobalNav.css = style
  return GlobalNav
}) satisfies QuartzComponentConstructor
