import type {
  QuartzComponent,
  QuartzComponentConstructor,
  QuartzComponentProps,
} from "@quartz-community/types"
import { resolveRelative } from "../util/path"
import style from "./styles/noteSpecs.scss"

/**
 * `reading-time`(content-meta가 쓰는 패키지)의 알고리즘을 그대로 옮긴 것.
 * 모바일(content-meta)과 데스크톱(SPECS)이 다른 숫자를 내면 안 되므로
 * 근사가 아니라 이식이다 — 카타카나 제외 같은 세부까지 같아야 값이 맞는다.
 * ⚠️ 패키지를 의존성으로 넣지 말 것: CJS라 ESM 번들에서
 * `Dynamic require of "stream" is not supported`로 컴포넌트 로드가 통째로 죽는다.
 */
function inRanges(code: number, ranges: [number, number][]): boolean {
  return ranges.some(([lo, hi]) => lo <= code && code <= hi)
}

// 카타카나는 원 패키지가 의도적으로 제외한다.
const isCJK = (c?: string): boolean =>
  typeof c === "string" &&
  inRanges(c.charCodeAt(0), [
    [0x3040, 0x309f],
    [0x4e00, 0x9fff],
    [0xac00, 0xd7a3],
    [0x20000, 0x2ebe0],
  ])

const isWordBound = (c?: string): boolean => typeof c === "string" && " \n\r\t".includes(c)

const isPunctuation = (c?: string): boolean =>
  typeof c === "string" &&
  inRanges(c.charCodeAt(0), [
    [0x21, 0x2f],
    [0x3a, 0x40],
    [0x5b, 0x60],
    [0x7b, 0x7e],
    [0x3000, 0x303f],
    [0xff00, 0xffef],
  ])

function countWords(text: string): number {
  let words = 0
  let start = 0
  let end = text.length - 1

  while (isWordBound(text[start])) start++
  while (end >= 0 && isWordBound(text[end])) end--

  const t = `${text}\n`
  for (let i = start; i <= end; i++) {
    if (isCJK(t[i]) || (!isWordBound(t[i]) && (isWordBound(t[i + 1]) || isCJK(t[i + 1])))) {
      words++
    }
    // CJK 뒤에 붙은 문장부호·공백은 같은 단어로 먹는다
    if (isCJK(t[i])) {
      while (i <= end && (isPunctuation(t[i + 1]) || isWordBound(t[i + 1]))) i++
    }
  }
  return words
}

/** recent-notes-index·note-catalog와 같은 슬러그 패턴 필터. */
function isAutoGeneratedPage(slug: string): boolean {
  return (
    slug.startsWith("tags/") ||
    slug === "index" ||
    slug.endsWith("/index") ||
    slug === "404" ||
    slug === "topics" ||
    slug === "archive"
  )
}

export interface NoteSpecsOptions {
  title: string
  labels: { date: string; runtime: string; topic: string }
}

const defaultOptions: NoteSpecsOptions = {
  title: "SPECS",
  labels: { date: "Recorded", runtime: "Runtime", topic: "Topic" },
}

/**
 * 우측 사이드바 최상단 스펙 블록 — 음반 슬리브의 사양 표기.
 * 제목 바로 아래에 뭉쳐 있던 날짜·읽기시간·태그를 여기로 옮겨
 * 제목에서 본문으로 가는 길을 비운다.
 */
export default ((userOpts?: Partial<NoteSpecsOptions>) => {
  const opts = { ...defaultOptions, ...userOpts }

  const NoteSpecs: QuartzComponent = ({ cfg, fileData }: QuartzComponentProps) => {
    const slug = fileData.slug
    if (!slug || isAutoGeneratedPage(slug)) return <></>

    const dates = fileData.dates as Record<string, Date> | undefined
    const date = dates?.modified ?? dates?.published ?? dates?.created
    const text = fileData.text as string | undefined
    const minutes = text ? Math.ceil(countWords(text) / 200) : 0
    const tags = (fileData.frontmatter?.tags ?? []) as string[]

    if (!date && !minutes && tags.length === 0) return <></>

    const locale = cfg.locale || "en-US"

    return (
      <aside class="note-specs">
        <h3 class="note-specs-title">{opts.title}</h3>
        <dl class="note-specs-list">
          {date && (
            <div class="note-specs-row">
              <dt>{opts.labels.date}</dt>
              <dd>
                <time datetime={date.toISOString()}>
                  {date.toLocaleDateString(locale, {
                    year: "numeric",
                    month: "short",
                    day: "2-digit",
                  })}
                </time>
              </dd>
            </div>
          )}
          {minutes > 0 && (
            <div class="note-specs-row">
              <dt>{opts.labels.runtime}</dt>
              <dd>{minutes} min</dd>
            </div>
          )}
          {tags.length > 0 && (
            <div class="note-specs-row">
              <dt>{opts.labels.topic}</dt>
              <dd class="note-specs-tags">
                {tags.map((tag) => (
                  <a key={tag} href={resolveRelative(slug, `tags/${tag}`)}>
                    {tag}
                  </a>
                ))}
              </dd>
            </div>
          )}
        </dl>
      </aside>
    )
  }

  NoteSpecs.css = style
  return NoteSpecs
}) satisfies QuartzComponentConstructor<Partial<NoteSpecsOptions>>
