import type {
  QuartzComponent,
  QuartzComponentConstructor,
  QuartzComponentProps,
  QuartzPluginData,
} from "@quartz-community/types"
import { classNames } from "@quartz-community/utils/lang"
import { formatDate } from "@quartz-community/utils/date"
import { resolveRelative } from "../util/path"
import style from "./styles/recentNotes.scss"

type RecentNotesPluginData = QuartzPluginData & Record<string, unknown>

/**
 * [2026-08-03 버그픽스] `frontmatter?.title` 유무만으로는 실제 콘텐츠 노트를
 * 걸러낼 수 없다 — `folder-page`/`tag-page`가 자동 생성한 페이지도 title이
 * 채워진다(예: `computer-science/algorithm/index` → title "algorithm").
 * 폴더 인덱스 페이지는 자식 노트 중 가장 최근 수정일을 물려받는 경우가 많아,
 * 정렬 시 실제 최근 글보다 위로 올라와 "Recent Notes"에 폴더 페이지가 섞여
 * 나올 수 있다(home-hero 작업 중 static/contentIndex.json 실측으로 발견 —
 * 총 147건 중 87건만 실제 노트, 나머지는 tags/ 하위(27) + /index로 끝나는 폴더(33)).
 */
function isAutoGeneratedPage(slug: string): boolean {
  // "404"도 frontmatter.title을 가진 특수 페이지라 위 조건만으로는 안 걸러짐
  // (home-hero 작업 중 실측으로 발견). "topics"/"archive"는 Phase 6에서 추가된
  // 가상 페이지(topics-page/archive-page)로 역시 frontmatter.title이 채워진
  // 채로 생성되어 같은 방식으로 걸러야 한다.
  return (
    slug.startsWith("tags/") ||
    slug === "index" ||
    slug.endsWith("/index") ||
    slug === "404" ||
    slug === "topics" ||
    slug === "archive"
  )
}

export interface RecentNotesForIndexOptions {
  title?: string
  limit: number
  linkToMore: string | false
  linkToMoreLabel: string
  showTags: boolean
  filter: (f: RecentNotesPluginData) => boolean
  sort: (f1: RecentNotesPluginData, f2: RecentNotesPluginData) => number
}

/**
 * v4 semantics preserved: sort by modified date, falling back to created
 * date, falling back to 0 (unset dates sort last). Deliberately NOT reusing
 * `@quartz-community/utils/sort`'s `byDateAndAlphabetical`, which only reads
 * a single `defaultDateType` with no modified→created fallback chain — see
 * MIGRATION-NOTES §15 decision note for this plugin.
 */
function getSortTime(f: RecentNotesPluginData): number {
  return f.dates?.modified?.getTime() ?? f.dates?.created?.getTime() ?? 0
}

function getDisplayDate(f: RecentNotesPluginData): Date | undefined {
  return f.dates?.modified ?? f.dates?.created ?? f.dates?.published
}

/**
 * [2026-08-03 재작성] 목업(haejun-redesign-abc.html:97-134, 128-136) 재확인
 * 결과 Recent Notes는 카드 그리드가 아니라 **행 리스트**였다 — 이전 구현은
 * v4에서 이식한 `note-card` 그리드를 그대로 썼는데, 목업의 실제 마크업
 * (`.rows > .row { grid-template-columns: 96px 1fr auto }`)과 달랐다.
 *
 * `.tag`도 카테고리명을 번역한 pill 여러 개가 아니라 **원본 tags[0] 문자열
 * 하나**(예: `computer-science/network`)를 그대로 보여준다. frontmatter에
 * 태그가 없는 노트를 위한 폴백으로 슬러그의 마지막 세그먼트(파일명)를 뺀
 * 나머지를 사용한다 — 목업의 "topic/subfolder" 형태와 동일한 모양이 된다.
 */
function getTagLabel(f: RecentNotesPluginData): string {
  const tags = f.frontmatter?.tags
  if (Array.isArray(tags) && tags.length > 0 && typeof tags[0] === "string") {
    return tags[0]
  }
  const slug = (f.slug as string | undefined) ?? ""
  const parts = slug.split("/")
  return parts.length > 1 ? parts.slice(0, -1).join("/") : (parts[0] ?? "")
}

const defaultOptions: RecentNotesForIndexOptions = {
  limit: 6,
  linkToMore: false,
  linkToMoreLabel: "아카이브 →",
  showTags: true,
  filter: () => true,
  sort: (f1, f2) => getSortTime(f2) - getSortTime(f1),
}

export default ((userOpts?: Partial<RecentNotesForIndexOptions>) => {
  const opts: RecentNotesForIndexOptions = { ...defaultOptions, ...userOpts }

  const RecentNotesForIndex: QuartzComponent = ({
    allFiles,
    fileData,
    displayClass,
    cfg,
  }: QuartzComponentProps) => {
    // Index-only guard. No built-in v5 layout `condition` matches "index page
    // only" — only the inverse, `not-index`, is built in (MIGRATION-NOTES §6)
    // — so this keeps the same internal-guard pattern v4 used.
    if (fileData.slug !== "index") return <></>

    const files = allFiles as RecentNotesPluginData[]
    const pages = files
      .filter(opts.filter)
      .filter(
        (f) =>
          f.slug !== fileData.slug && f.frontmatter?.title && !isAutoGeneratedPage(f.slug ?? ""),
      )
      .sort(opts.sort)
      .slice(0, opts.limit)

    const locale = cfg.locale ?? "en-US"

    return (
      // [2026-08-03] id="recent" — home-hero의 "노트 둘러보기" CTA(href="#recent")가
      // 스크롤 대상으로 참조한다.
      <div id="recent" class={classNames(displayClass, "recent-notes")}>
        <div class="recent-notes-header">
          <h2>{opts.title ?? "Recent Notes"}</h2>
          {opts.linkToMore && (
            <a class="recent-notes-more" href={resolveRelative(fileData.slug!, opts.linkToMore)}>
              {opts.linkToMoreLabel}
            </a>
          )}
        </div>
        <div class="rows">
          {pages.map((page) => {
            const title = page.frontmatter?.title ?? "Untitled"
            const description = page.description ?? ""
            const displayDate = getDisplayDate(page)

            return (
              <a class="row" href={resolveRelative(fileData.slug!, page.slug!)}>
                <span class="d">{displayDate ? formatDate(displayDate, locale) : ""}</span>
                <span>
                  <span class="t">{title}</span>
                  {description && <span class="s">{description}</span>}
                </span>
                {opts.showTags && <span class="tag">{getTagLabel(page)}</span>}
              </a>
            )
          })}
        </div>
      </div>
    )
  }

  RecentNotesForIndex.css = style
  return RecentNotesForIndex
}) satisfies QuartzComponentConstructor<Partial<RecentNotesForIndexOptions>>
