import type {
  QuartzComponent,
  QuartzComponentConstructor,
  QuartzComponentProps,
  QuartzPluginData,
} from "@quartz-community/types"
import { classNames } from "@quartz-community/utils/lang"
import { formatDate } from "@quartz-community/utils/date"
import { resolveRelative } from "../util/path"
import style from "./styles/recentNotes.scss"

type RecentNotesPluginData = QuartzPluginData & Record<string, unknown>

/** 슬러그 패턴으로 거른다. 자동 생성 페이지도 title이 있어 title 유무로는 안 된다. */
function isAutoGeneratedPage(slug: string): boolean {
  return (
    slug.startsWith("tags/") ||
    slug === "index" ||
    slug.endsWith("/index") ||
    slug === "404" ||
    slug === "topics" ||
    slug === "archive"
  )
}

export interface RecentNotesForIndexOptions {
  title?: string
  limit: number
  linkToMore: string | false
  linkToMoreLabel: string
  showTags: boolean
  filter: (f: RecentNotesPluginData) => boolean
  sort: (f1: RecentNotesPluginData, f2: RecentNotesPluginData) => number
}

/**
 * modified → created → 0(날짜 없으면 뒤로).
 * utils의 `byDateAndAlphabetical`을 쓰지 않는 건 의도적 — 그쪽은
 * defaultDateType 하나만 읽고 modified→created 폴백 체인이 없다.
 */
function getSortTime(f: RecentNotesPluginData): number {
  return f.dates?.modified?.getTime() ?? f.dates?.created?.getTime() ?? 0
}

function getDisplayDate(f: RecentNotesPluginData): Date | undefined {
  return f.dates?.modified ?? f.dates?.created ?? f.dates?.published
}

/**
 * 태그 칸은 pill 여러 개가 아니라 원본 tags[0] 문자열 하나를 그대로 쓴다
 * (예: `computer-science/network`).
 * 태그가 없으면 슬러그에서 파일명만 뗀 나머지로 폴백 — 같은 "topic/subfolder" 모양.
 */
function getTagLabel(f: RecentNotesPluginData): string {
  const tags = f.frontmatter?.tags
  if (Array.isArray(tags) && tags.length > 0 && typeof tags[0] === "string") {
    return tags[0]
  }
  const slug = (f.slug as string | undefined) ?? ""
  const parts = slug.split("/")
  return parts.length > 1 ? parts.slice(0, -1).join("/") : (parts[0] ?? "")
}

const defaultOptions: RecentNotesForIndexOptions = {
  limit: 6,
  linkToMore: false,
  linkToMoreLabel: "아카이브 →",
  showTags: true,
  filter: () => true,
  sort: (f1, f2) => getSortTime(f2) - getSortTime(f1),
}

export default ((userOpts?: Partial<RecentNotesForIndexOptions>) => {
  const opts: RecentNotesForIndexOptions = { ...defaultOptions, ...userOpts }

  const RecentNotesForIndex: QuartzComponent = ({
    allFiles,
    fileData,
    displayClass,
    cfg,
  }: QuartzComponentProps) => {
    // 홈 전용 가드. `is-index` layout condition은 내장에 없다(역인 not-index만 존재).
    if (fileData.slug !== "index") return <></>

    const files = allFiles as RecentNotesPluginData[]
    const pages = files
      .filter(opts.filter)
      .filter(
        (f) =>
          f.slug !== fileData.slug && f.frontmatter?.title && !isAutoGeneratedPage(f.slug ?? ""),
      )
      .sort(opts.sort)
      .slice(0, opts.limit)

    const locale = cfg.locale ?? "en-US"

    return (
      // id="recent" — home-hero의 CTA(href="#recent") 스크롤 대상. 지우지 말 것.
      <div id="recent" class={classNames(displayClass, "recent-notes")}>
        <div class="recent-notes-header">
          <h2>{opts.title ?? "Recent Notes"}</h2>
          {opts.linkToMore && (
            <a class="recent-notes-more" href={resolveRelative(fileData.slug!, opts.linkToMore)}>
              {opts.linkToMoreLabel}
            </a>
          )}
        </div>
        <div class="rows">
          {pages.map((page) => {
            const title = page.frontmatter?.title ?? "Untitled"
            const description = page.description ?? ""
            const displayDate = getDisplayDate(page)

            return (
              <a class="row" href={resolveRelative(fileData.slug!, page.slug!)}>
                <span class="d">{displayDate ? formatDate(displayDate, locale) : ""}</span>
                <span>
                  <span class="t">{title}</span>
                  {description && <span class="s">{description}</span>}
                </span>
                {opts.showTags && <span class="tag">{getTagLabel(page)}</span>}
              </a>
            )
          })}
        </div>
      </div>
    )
  }

  RecentNotesForIndex.css = style
  return RecentNotesForIndex
}) satisfies QuartzComponentConstructor<Partial<RecentNotesForIndexOptions>>
