import type {
  QuartzComponent,
  QuartzComponentConstructor,
  QuartzComponentProps,
  QuartzPluginData,
} from "@quartz-community/types"
import { resolveRelative } from "../util/path"
import style from "./styles/noteCatalog.scss"
// @ts-expect-error - Inline script loaded as text by esbuild plugin
import graphFoldScript from "./scripts/graphFold.inline.ts"

type CatalogPluginData = QuartzPluginData & Record<string, unknown>

/**
 * ⚠️ `frontmatter.title` 유무로는 실제 노트를 걸러낼 수 없다 — folder-page /
 * tag-page 자동 생성 페이지, 404, topics/archive 가상 페이지 모두 title이 있다.
 * recent-notes-index와 같은 슬러그 패턴 필터를 쓴다.
 */
function isAutoGeneratedPage(slug: string): boolean {
  return (
    slug.startsWith("tags/") ||
    slug === "index" ||
    slug.endsWith("/index") ||
    slug === "404" ||
    slug === "topics" ||
    slug === "archive"
  )
}

export interface NoteCatalogOptions {
  title: string
  moreHref: string
  moreLabel: string
}

const defaultOptions: NoteCatalogOptions = {
  title: "CATALOG",
  moreHref: "topics",
  moreLabel: "← 모든 토픽 보기",
}

/**
 * 좌측 패널 — 전체 파일 트리 대신 현재 노트의 형제 노트만 보여준다.
 * 길이가 형제 수에만 비례하므로 노트가 늘어도 한 화면을 넘지 않고,
 * 펼침 상태가 없어 explorer의 localStorage 누적 문제가 발생하지 않는다.
 */
export default ((userOpts?: Partial<NoteCatalogOptions>) => {
  const opts = { ...defaultOptions, ...userOpts }

  const NoteCatalog: QuartzComponent = ({ fileData, allFiles }: QuartzComponentProps) => {
    const currentSlug = fileData.slug
    if (!currentSlug || isAutoGeneratedPage(currentSlug)) return <></>

    const parentDir = currentSlug.split("/").slice(0, -1).join("/")

    // 번호 접두사(`1. `, `2. `)가 사용자 의도한 순서라 날짜가 아닌 자연 정렬을 쓴다.
    const siblings = (allFiles as CatalogPluginData[])
      .filter((f) => {
        if (!f.slug || isAutoGeneratedPage(f.slug)) return false
        return f.slug.split("/").slice(0, -1).join("/") === parentDir
      })
      .sort((a, b) =>
        (a.frontmatter?.title ?? a.slug!).localeCompare(b.frontmatter?.title ?? b.slug!, undefined, {
          numeric: true,
          sensitivity: "base",
        }),
      )

    if (siblings.length === 0) return <></>

    return (
      <nav class="note-catalog" aria-label={opts.title}>
        <h2 class="note-catalog-title">{opts.title}</h2>
        {parentDir && (
          <a class="note-catalog-path" href={resolveRelative(currentSlug, `${parentDir}/index`)}>
            {parentDir.split("/").join(" / ")}
          </a>
        )}
        <ul class="note-catalog-list">
          {siblings.map((f) => {
            const isCurrent = f.slug === currentSlug
            return (
              <li key={f.slug}>
                <a
                  class={isCurrent ? "note-catalog-link active" : "note-catalog-link"}
                  href={resolveRelative(currentSlug, f.slug!)}
                  aria-current={isCurrent ? "page" : undefined}
                >
                  {f.frontmatter?.title ?? f.slug!.split("/").pop()}
                </a>
              </li>
            )
          })}
        </ul>
        <a class="note-catalog-more" href={resolveRelative(currentSlug, opts.moreHref)}>
          {opts.moreLabel}
        </a>
      </nav>
    )
  }

  NoteCatalog.css = style
  // ⚠️ 우측 graph 접기 스크립트가 여기 붙어 있는 이유: config-loader는 플러그인
  // 엔트리 하나당 컴포넌트 하나만 배치하므로(config-loader.ts:753) 스크립트
  // 전용 컴포넌트를 따로 둘 수 없다. DesktopOnly/ConditionalRender 래퍼는
  // beforeDOMLoaded를 보존하므로 layout 조건이 붙어도 스크립트는 실린다.
  NoteCatalog.beforeDOMLoaded = graphFoldScript
  return NoteCatalog
}) satisfies QuartzComponentConstructor<Partial<NoteCatalogOptions>>
